tool: LIRICAL
tool_version: 2.0.0-RC2
variant_analysis: True
gene_analysis: True
disease_analysis: False
tool_specific_configuration_options:
  mode: manual
  lirical_jar_executable: lirical-cli-2.0.0-RC2/lirical-cli-2.0.0-RC2.jar
  exomiser_db_configurations:
    exomiser_database:
    exomiser_hg19_database: 2209_hg19_variants.mv.db
    exomiser_hg38_database:
  post_process:
    sort_order: descending