run:
  environment: local
  phenotype_only: False
  version: 1.3.4
  path_to_lirical_software_directory: /Users/yaseminbridges/lirical/lirical-cli-2.0.0-RC1/lirical-cli-2.0.0-RC1.jar
  exomiser_configurations:
    path_to_exomiser_data_directory: /Users/yaseminbridges/exomiser/data/2209_hg19/2209_hg19_variants.mv.db
post_process:
  sort_order: descending